# Generated by Django 5.0.6 on 2024-05-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_Page_Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slider", models.ImageField(upload_to="slider_images/")),
            ],
        ),
    ]
