# Generated by Django 5.0.6 on 2024-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0002_home_page_slider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="subject",
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
