# Generated by Django 5.0.6 on 2024-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0003_remove_contactmessage_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone_number",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
