# Generated by Django 5.0.6 on 2024-05-24 10:39

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0004_contactmessage_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_Us_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
