# Generated by Django 5.0.6 on 2024-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0006_mission_and_vison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission_and_vison",
            name="mission",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="mission_and_vison",
            name="vision",
            field=models.CharField(max_length=100000),
        ),
    ]
