# Generated by Django 5.0.6 on 2024-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0007_alter_mission_and_vison_mission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturing_and_Related_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Services/Manufacturing_and_Related_Service/"
                    ),
                ),
            ],
        ),
    ]
