# Generated by Django 5.0.6 on 2024-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0008_manufacturing_and_related_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_Registration_Consulting_Setup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Services/Business_Registration_Consulting_Setup/"
                    ),
                ),
            ],
        ),
    ]
