# Generated by Django 5.0.6 on 2024-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0009_business_registration_consulting_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media_and_Innovative_Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Services/Media_and_Innovative_Designer/"
                    ),
                ),
            ],
        ),
    ]
