# Generated by Django 5.0.6 on 2024-05-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lpclApp", "0010_media_and_innovative_designer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects_and_Technical_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Services/Projects_and_Technical_Service/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Travel_Support_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="Services/Travel_Support_Service/"),
                ),
            ],
        ),
    ]
